### ISSUE TITLE
change s2?

### ISSUE THREAD

**Issue by jimmywarting** [stoffern/pokemon-go-api#16]
Pokemon-GO-node-api used a es6 [ported version](https://github.com/billyriantono/simple-s2-node) of s2 before but decided to change that once the were going back to es5

So now  they used [s2geometry-node](https://github.com/billyriantono/s2geometry-node) which is a C binding version.

It's not pure js and requires building.
It has it pro&con maybe faster more robust? but the negative part is that it can take long time to build and may fail on some OS

But i don't know so much about s2 and the api that is available from it

**Comment by stoffern** [comment]
@jimmywarting I have looked into S2 and how it works.
It is quite big and has alot of functions that will take alot of time to port.
the c++ version is also faster.

Since it compiles fine for both windows, linux and mac now, i think we should keep using s2geometry-node

**Comment by jimmywarting** [comment]
Okey!
