### ISSUE TITLE
Error: No endPoint set!

### ISSUE THREAD

**Issue by jimmywarting** [stoffern/pokemon-go-api#3]
guess endpoint is never set?

**Comment by stoffern** [comment]
it does here:
https://github.com/stoffern/pokemon-go-api/blob/81d08e27165f3ee33d21307f6afac365b897a320/src/API.js#L16
then it changes endpoint for every query

**Comment by jimmywarting** [comment]
then shouldn't `this.endpoint` be `this.endPoint`?

https://github.com/stoffern/pokemon-go-api/blob/81d08e27165f3ee33d21307f6afac365b897a320/src/API.js#L24

**Comment by stoffern** [comment]
@jimmywarting yeah, thats correct, fixing it now

**Comment by jimmywarting** [comment]
thanks

**Comment by stoffern** [comment]
@jimmywarting please note that `.Call()` function is not finished yet. the headers is not correct setup yet

**Comment by jimmywarting** [comment]
Ah, then I went ahead of my self and played with it to much 😄

**Comment by stoffern** [comment]
np :smiley:

**Comment by stoffern** [comment]
fixed
