### ISSUE TITLE
tab & tab size 4?

### ISSUE THREAD

**Issue by jimmywarting** [stoffern/pokemon-go-api#4]
are you using 2 spaces because the previous repo used spaces and only used tab size == 2?

My preference is to use 1 tab and have tab size = 4

And i guess many other feel the same way about the tab size should equal to 4?
tab vs spaces is a other discussion that can be hard to debate - which only comes down to the owners choice

Right now there is a mix of spaces and tabs, a bit anoying

**Comment by stoffern** [comment]
spaces over tabs.. when you copy, pase, move around code ... tabs are different viewd on github, bitbucket and so on.

spaces are consistant.
editors lets you coose 2, 4, 10 spaces for each indent.. thats up to you to set in your editor.

**Comment by jimmywarting** [comment]
in isaacs/github#170 they say you can put a .editorconfig file in your repo to say how github should render the view

**Comment by stoffern** [comment]
@jimmywarting thats for GitHub what about source-code posting on other websites?
i went from tabs to spaces, and are not going back! :smile:

end of discussion

**Comment by stoffern** [comment]
@jimmywarting just change your indention in you editor to spaces and the distance you use.

problem solved :smile:

**Comment by jimmywarting** [comment]
sure space it is. but how many space do you want? 2, 4?

**Comment by stoffern** [comment]
Using 2 as it is has become Facebook and nodesjs`s standards
